version: '3.8'

services:
  web-psmo24:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: psmo24_web_php
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
    volumes:
      - ./logs:/var/log/apache2
    networks:
      - psmo24_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.psmo24.rule=Host(`psmo24.kz`)"
      - "traefik.http.routers.psmo24.entrypoints=websecure"
      - "traefik.http.routers.psmo24.tls.certresolver=myresolver"

networks:
  psmo24_network:
    driver: bridge 