version: '3.8'

services:
  psmo24-web:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: psmo24_web_php
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      - ./logs:/var/log/apache2
    networks:
      - psmo24_network

  # Опционально: добавляем mailhog для тестирования почты
  mailhog:
    image: mailhog/mailhog:latest
    container_name: psmo24_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - psmo24_network

networks:
  psmo24_network:
    driver: bridge 